SELECT* FROM LOP
SELECT* FROM MONHOC
SELECT* FROM DIEUKIEN
SELECT* FROM KHOA
SELECT* FROM HOCVIEN
SELECT* FROM GIANGDAY
SELECT* FROM KETQUATHI
SELECT* FROM GIAOVIEN

ALTER TABLE LOP NOCHECK CONSTRAINT ALL
ALTER TABLE LOP CHECK CONSTRAINT ALL 

--Trigger: I.9,10 & 15->24

/*I. Data Definition Language*/
/*Câu 1: Tạo quan hệ và khai báo tất cả các ràng buộc khóa chính, khóa ngoại. Thêm vào 3 thuộc tính
GHICHU, DIEMTB, XEPLOAI cho quan hệ HOCVIEN.*/
ALTER TABLE HOCVIEN ADD GHICHU VARCHAR(40)
ALTER TABLE HOCVIEN ADD DIEMTB TINYINT
ALTER TABLE HOCVIEN ADD XEPLOAI VARCHAR(10)

ALTER TABLE HOCVIEN DROP COLUMN GHICHU
ALTER TABLE HOCVIEN DROP COLUMN DIEMTB
ALTER TABLE HOCVIEN DROP COLUMN XEPLOAI

ALTER TABLE HOCVIEN ALTER COLUMN MAHV VARCHAR(5)

/*Câu 3: Thuộc tính GIOITINH chỉ có giá trị là “Nam” hoặc “Nu”.*/
ALTER TABLE HOCVIEN  ADD CONSTRAINT HOCVIEN_GIOITINH_CK 
CHECK(GIOITINH IN ('Nam','Nu'))
ALTER TABLE GIAOVIEN  ADD CONSTRAINT GIANGVIEN_GIOITINH_CK 
CHECK(GIOITINH IN ('Nam','Nu'))

/*Câu 4: Điểm số của một lần thi có giá trị từ 0 đến 10 và cần lưu đến 2 số lẽ (VD: 6.22).*/
ALTER TABLE KETQUATHI ADD CONSTRAINT KQT_DIEM_CK 
CHECK((DIEM BETWEEN 0 AND 10))

--Câu 5
ALTER TABLE KETQUATHI ADD CONSTRAINT KQT_DIEM_KQUA_CK
CHECK(((DIEM BETWEEN 5 AND 10) AND KQUA = 'Dat') OR ((DIEM < 5 AND KQUA = 'Khong dat')))

--Câu 6
ALTER TABLE KETQUATHI ADD CONSTRAINT KQT_LANTHI_CK
CHECK(LANTHI <= 3)

--Câu 7
ALTER TABLE GIANGDAY ADD CONSTRAINT GIANGDAY_HOCKY_CK
CHECK(HOCKY BETWEEN 1 AND 3)

--Câu 8
ALTER TABLE GIAOVIEN ADD CONSTRAINT GIAOVIEN_HOCVI_CK
CHECK(HOCVI IN ('CN', 'KS', 'Ths', 'TS', 'PTS'))

/*Câu 9: Lớp trưởng của một lớp phải là học viên của lớp đó.*/
GO
CREATE TRIGGER TRG_LOP_THESUA_TRGLOP ON LOP
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @TRGLOP CHAR(5),
			@MALOP1 CHAR(3),
			@MALOP2 CHAR(3)

	SELECT @TRGLOP = TRGLOP, @MALOP1 = MALOP
	FROM INSERTED

	SELECT @MALOP2 = MALOP
	FROM HOCVIEN
	WHERE MAHV = @TRGLOP

	IF(@MALOP1 <> @MALOP2)
	BEGIN
		PRINT 'LOI: LOP TRUONG CUA 1 LOP PHAI LA HOC VIEN LOP DO'
		ROLLBACK TRANSACTION
	END
END
--Kiểm tra dữ liệu
UPDATE LOP
SET TRGLOP = 'K1202' --Error
WHERE MALOP = 'K11'

GO
CREATE TRIGGER HOCVIEN_XOASUA_MALOP ON HOCVIEN
FOR DELETE, UPDATE
AS 
BEGIN
	DECLARE @TRGLOP CHAR(5),
			@MAHV CHAR(5),
			@MALOP1 CHAR(3),
			@MALOP2 CHAR(3)

	SELECT @MAHV = MAHV
	FROM INSERT

--Câu 11
ALTER TABLE HOCVIEN ADD CHECK(YEAR(GETDATE()) - YEAR(NGSINH) >= 18)

--Câu 12
ALTER TABLE GIANGDAY ADD CONSTRAINT GIANGDAY_TUNGAY_DENGAY_CK
CHECK(TUNGAY < DENNGAY) 

DELETE FROM GIANGDAY
ALTER TABLE GIANGDAY DROP CONSTRAINT GIANGDAY_TUNGAY_DENGAY_CK

--Câu 13
ALTER TABLE GIAOVIEN ADD CHECK(YEAR(GETDATE()) - YEAR(NGSINH) >= 22)

--Câu 14
ALTER TABLE MONHOC ADD CONSTRAINT MONHOC_TCLT_TCTH_CK
CHECK(ABS(TCLT - TCTH) <= 3 OR TCTH = 0) /*If there isn't "OR TCTH = 0", it won't meet the given dataset*/ 

DELETE FROM MONHOC
ALTER TABLE MONHOC DROP CONSTRAINT MONHOC_TCLT_TCTH_CK


/*15. Học viên chỉ được thi một môn học nào đó khi lớp của học viên đã học xong môn học này.*/

/*16. Mỗi học kỳ của một năm học, một lớp chỉ được học tối đa 3 môn.*/
GO
CREATE TRIGGER TRG_GIANGDAY_COUNTMAMH_INS_UPD ON GIANGDAY
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @MALOP CHAR(3),
			@TongSoMH SMALLINT,
			@HOCKY TINYINT,
			@NAM SMALLINT

	SELECT @MALOP = MALOP, @HOCKY = HOCKY, @NAM = NAM
	FROM INSERTED

	SELECT @TongSoMH = COUNT(MAMH)
	FROM GIANGDAY
	WHERE MALOP = @MALOP AND HOCKY = @HOCKY AND NAM = @NAM

	IF(@TongSoMH > 3)
	BEGIN
		PRINT('LOI: MOI HOC KY CUA MOT NAM HOC, MOT LOP CHI DUOC HOC TOI DA 3 MON')
		ROLLBACK TRANSACTION
	END
END
--Kiểm tra Trigger
SELECT* FROM GIANGDAY
INSERT INTO GIANGDAY VALUES('K11','PTTKHTTT','GV04',1,2007,null,null)

/*17. Sỉ số của một lớp bằng với số lượng học viên thuộc lớp đó.*/
GO
CREATE TRIGGER TRG_LOP_SISO_UPD ON LOP
FOR UPDATE
AS
BEGIN
	DECLARE @SISO TINYINT,
			@SLHocVien TINYINT,
			@MALOP CHAR(3)

	SELECT @MALOP = MALOP, @SISO = SISO
	FROM INSERTED

	SELECT @SLHocVien = COUNT(MAHV)
	FROM HOCVIEN
	WHERE MALOP = @MALOP

	IF(@SLHocVien <> @SISO)
	BEGIN
		PRINT('TRG_LOP_SISO_UPD: SI SO CUA MOT LOP BANG SO LUONG HOC VIEN THUOC LOP DO')
		ROLLBACK TRANSACTION
	END
END
--Kiểm tra Trigger
SELECT COUNT(MAHV) FROM HOCVIEN WHERE MALOP = 'K11'
UPDATE LOP
SET SISO = 12
WHERE MALOP = 'K11'

GO
CREATE TRIGGER TRG_HOCVIEN_MALOP_INS_DEL_UDP ON HOCVIEN
FOR INSERT, UPDATE, DELETE
AS
BEGIN
	DECLARE @MALOP1 CHAR(3),
			@MALOP2 CHAR(3),
			@SISO TINYINT

	SELECT @MALOP1 = MALOP
	FROM INSERTED

	SELECT @MALOP2 = MALOP
	FROM DELETED

	IF EXISTS( SELECT* FROM INSERTED) AND EXISTS(SELECT* FROM DELETED)
	BEGIN 
		UPDATE LOP
		SET SISO = SISO + 1
		WHERE MALOP = @MALOP1

		UPDATE LOP
		SET SISO = SISO - 1
		WHERE MALOP = @MALOP2
		
		PRINT('UPDATE HOC VIEN THANH CONG')
	END

	IF EXISTS( SELECT* FROM INSERTED) AND NOT EXISTS(SELECT* FROM DELETED)
	BEGIN 
		UPDATE LOP
		SET SISO = SISO + 1
		WHERE MALOP = @MALOP1

		PRINT('THEM HOC VIEN THANH CONG')
	END

	IF NOT EXISTS( SELECT* FROM INSERTED) AND EXISTS(SELECT* FROM DELETED)
	BEGIN 
		UPDATE LOP
		SET SISO = SISO - 1
		WHERE MALOP = @MALOP2

		PRINT('XOA HOC VIEN THANH CONG')
	END
END 
--Kiểm tra Trigger
SELECT* FROM HOCVIEN
INSERT INTO HOCVIEN VALUES('K1112','Nguyen Thi','B',null,'Nu',null,'K11',null,null,null)
SELECT* FROM LOP
DELETE FROM HOCVIEN WHERE MAHV = 'K1112'
UPDATE HOCVIEN
SET MALOP = 'K13'
WHERE MAHV = 'K1112'

/*18. Trong quan hệ DIEUKIEN giá trị của thuộc tính MAMH và MAMH_TRUOC trong cùng một bộ
không được giống nhau (“A”,”A”) và cũng không tồn tại hai bộ (“A”,”B”) và (“B”,”A”).*/
GO
CREATE TRIGGER TRG_DIEUKIEN_KTGIONGNHAU ON DIEUKIEN
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @MAMH VARCHAR(10),
			@MAMH_TRUOC VARCHAR(10)

	SELECT @MAMH = MAMH, @MAMH_TRUOC = MAMH_TRUOC
	FROM INSERTED

	IF(@MAMH = @MAMH_TRUOC)
	BEGIN
		PRINT('TRG_DIEUKIEN_KTGIONGNHAU: MAMH VA MAMH_TRUOC TRONG CUNG MOT BO KHONG DUOC GIONG NHAU.')
		ROLLBACK TRANSACTION
	END
END
--Kiểm tra Trigger
INSERT INTO DIEUKIEN VALUES('GT','GT')

/*Cách 1: Dùng IF EXISTS*/
GO
CREATE TRIGGER TRG_DIEUKIEN_KTTONTAIGIONGNHAU ON DIEUKIEN
FOR INSERT, UPDATE
AS
BEGIN
	IF EXISTS(	SELECT*
				FROM DIEUKIEN DK, INSERTED I
				WHERE DK.MAMH = I.MAMH_TRUOC AND DK.MAMH_TRUOC = I.MAMH)
	BEGIN
		PRINT('TRG_DIEUKIEN_KTTONTAIGIONGNHAU: MAMH VA MAMH_TRUOC KHONG CUNG TON TAI HAI BO  (“A”,”B”) và (“B”,”A”).')
		ROLLBACK TRANSACTION
	END
END
--Kiểm tra Trigger
SELECT* FROM DIEUKIEN
INSERT INTO DIEUKIEN VALUES('CTRR','CSDL')

/*Cách 2: Dùng CURSOR*/
GO
CREATE TRIGGER TRG_DIEUKIEN_KTTONTAIGIONGNHAU2 ON DIEUKIEN
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @MAMH VARCHAR(10),
			@MAMH_TRUOC VARCHAR(10)

	SELECT @MAMH = MAMH, @MAMH_TRUOC = MAMH_TRUOC
	FROM INSERTED

	DECLARE cur_DIEUKIEN CURSOR FOR
		SELECT MAMH_TRUOC
		FROM DIEUKIEN
		WHERE MAMH = @MAMH_TRUOC

	OPEN cur_DIEUKIEN
	FETCH NEXT FROM cur_DIEUKIEN INTO @MAMH_TRUOC

	WHILE @@FETCH_STATUS = 0
	BEGIN
		IF(@MAMH_TRUOC = @MAMH)
		BEGIN 
			PRINT('TRG_DIEUKIEN_KTTONTAIGIONGNHAU2: MAMH VA MAMH_TRUOC KHONG CUNG TON TAI HAI BO  (“A”,”B”) và (“B”,”A”).')
			ROLLBACK TRANSACTION
		END
		ELSE
		BEGIN
			FETCH NEXT FROM cur_DIEUKIEN INTO @MAMH_TRUOC
		END
	END

	CLOSE cur_DIEUKIEN
	DEALLOCATE cur_DIEUKIEN
END
--Kiểm tra Trigger
SELECT* FROM DIEUKIEN
INSERT INTO DIEUKIEN VALUES('THDC','DHMT')

/*19. Các giáo viên có cùng học vị, học hàm, hệ số lương thì mức lương bằng nhau.*/
/*Cách 1*/
GO 
CREATE TRIGGER TRG_GIAOVIEN_HVHH_HESO_INS_UPD ON GIAOVIEN
FOR INSERT, UPDATE
AS
BEGIN
	IF EXISTS(	SELECT*
				FROM GIAOVIEN GV, INSERTED I
				WHERE I.HOCHAM = GV.HOCHAM
				AND I.HOCVI = GV.HOCVI
				AND I.HESO = GV.HESO
				AND I.MUCLUONG <> GV.MUCLUONG)
	BEGIN
		PRINT('TRG_GIAOVIEN_HVHH_HESO_INS_UPD: GV CO CUNG HOC VI, HOC HAM, HESOLUONG THI MUC LUONG BANG NHAU')
		ROLLBACK TRANSACTION
	END
END

/*Cách 2*/ --Sai
GO 
CREATE TRIGGER TRG_GIAOVIEN_HVHH_HESO_INS_UPD2 ON GIAOVIEN
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @HOCVI VARCHAR(10),	
			@HOCHAM VARCHAR(10),
			@HESO NUMERIC(4,2),
			@MAGV CHAR(4),
			@MUCLUONG MONEY,
			@HOCVI_cur VARCHAR(10),	
			@HOCHAM_cur VARCHAR(10),
			@MUCLUONG_cur MONEY,
			@HESO_cur NUMERIC(4,2)

	SELECT @HOCVI = HOCVI, @HOCHAM = HOCHAM, @HESO = HESO, @MUCLUONG = MUCLUONG
	FROM INSERTED

	DECLARE cur_GIAOVIEN CURSOR FOR
		SELECT MAGV
		FROM GIAOVIEN

	OPEN cur_GIAOVIEN
	FETCH NEXT FROM cur_GIAOVIEN INTO @MAGV

	WHILE @@FETCH_STATUS = 0
	BEGIN 
		SELECT @HOCVI_cur = HOCVI, @HOCHAM_cur = HOCHAM, @HESO_cur = HESO, @MUCLUONG_cur = MUCLUONG
		FROM GIAOVIEN
		WHERE MAGV = @MAGV

		IF(@HOCVI = @HOCVI_cur AND @HOCHAM = @HOCHAM_cur AND @HESO_cur = @HESO AND @MUCLUONG <> @MUCLUONG_cur)
		BEGIN
			PRINT('TRG_GIAOVIEN_HVHH_HESO_INS_UPD2: GV CO CUNG HOC VI, HOC HAM, HESOLUONG THI MUC LUONG BANG NHAU')
			ROLLBACK TRANSACTION
		END
		ELSE
		BEGIN 
			FETCH NEXT FROM cur_GIAOVIEN INTO @MAGV
		END
	END

	CLOSE cur_GIAOVIEN
	DEALLOCATE cur_GIAOVIEN
END

--Kiểm tra Trigger 
SELECT* FROM GIAOVIEN
DELETE FROM GIAOVIEN WHERE MAGV = 'GV16'
INSERT INTO GIAOVIEN VALUES('GV16','Nguyen Van C','PTS','GS','Nam',NULL,NULL,6.00,3250000.00,'KHMT')
DROP TRIGGER TRG_GIAOVIEN_HVHH_HESO_INS_UPD2

/*II. Data Manipulation Language*/
/*Câu 1: Tăng hệ số lương thêm 0.2 cho những giáo viên là trưởng khoa.*/
UPDATE GIAOVIEN
SET HESO = 1.2 * HESO
WHERE MAGV IN(	SELECT TRGKHOA
				FROM KHOA)

/*Câu 2: Cập nhật giá trị điểm trung bình tất cả các môn học (DIEMTB) của mỗi học viên (tất cả các môn
học đều có hệ số 1 và nếu học viên thi một môn nhiều lần, chỉ lấy điểm của lần thi sau cùng).*/
-- Nên tự làm lại
UPDATE HOCVIEN
SET DIEMTB = (	SELECT AVG(DIEM)
				FROM (	SELECT MAHV, MAMH, MAX(LANTHI) MAX_LANTHI
						FROM KETQUATHI
						GROUP BY MAHV, MAMH ) A, KETQUATHI B
				WHERE A.MAHV = B.MAHV AND MAX_LANTHI = B.LANTHI
				GROUP BY B.MAHV
				HAVING B.MAHV = HOCVIEN.MAHV)

--Forum
UPDATE HOCVIEN
SET DIEMTB = (	SELECT AVG(DIEM)
                FROM KETQUATHI K1
                WHERE LANTHI = (SELECT MAX(LANTHI)
                                FROM KETQUATHI K2
                                WHERE (K1.MAHV = K2.MAHV AND K1.MAMH = K2.MAMH)
                                GROUP BY MAHV,MAMH)
                GROUP BY MAHV
                HAVING MAHV = HOCVIEN.MAHV) 

/*Câu 3: Cập nhật giá trị cho cột GHICHU là “Cam thi” đối với trường hợp: học viên có một môn bất kỳ thi
lần thứ 3 dưới 5 điểm.*/
--Cách 1
UPDATE HOCVIEN
SET GHICHU = 'Cam thi'
WHERE MAHV IN(	SELECT MAHV
				FROM KETQUATHI KQT 
				WHERE DIEM < 5 AND LANTHI = 3 )

--Cách 2
UPDATE HOCVIEN
SET GHICHU = 'Cam thi'
FROM KETQUATHI KQT JOIN HOCVIEN HV ON KQT.MAHV = HV.MAHV
WHERE DIEM < 5 AND LANTHI = 3 

/*Câu 4: Cập nhật giá trị cho cột XEPLOAI trong quan hệ HOCVIEN như sau:
--o Nếu DIEMTB >= 9 thì XEPLOAI =”XS”*/
UPDATE HOCVIEN
SET XEPLOAI = 'XS'
WHERE DIEMTB >= 9

--o Nếu 8 <= DIEMTB < 9 thì XEPLOAI = “G”
UPDATE HOCVIEN
SET XEPLOAI = 'G'
WHERE DIEMTB >= 8 AND DIEMTB < 9

--o Nếu 6.5 <= DIEMTB < 8 thì XEPLOAI = “K”
UPDATE HOCVIEN
SET XEPLOAI = 'K'
WHERE DIEMTB >= 6.5 AND DIEMTB < 8

--o Nếu 5 <= DIEMTB < 6.5 thì XEPLOAI = “TB”
UPDATE HOCVIEN
SET XEPLOAI = 'TB'
WHERE DIEMTB >= 5 AND DIEMTB < 6.5

--o Nếu DIEMTB < 5 thì XEPLOAI = ”Y”
UPDATE HOCVIEN
SET XEPLOAI = 'Y'
WHERE DIEMTB < 5

/*III. Data Access Language*/
/*Câu 1: In ra danh sách (mã học viên, họ tên, ngày sinh, mã lớp) lớp trưởng của các lớp.*/
--Cách 1
SELECT HV.MAHV, HO, TEN, NGSINH, L.MALOP
FROM LOP L, HOCVIEN HV
WHERE L.TRGLOP = HV.MAHV

--Cách 2
SELECT HV.MAHV, HO, TEN, NGSINH, L.MALOP
FROM LOP L INNER JOIN HOCVIEN HV ON L.TRGLOP = HV.MAHV

/*Câu 2: In ra bảng điểm khi thi (mã học viên, họ tên , lần thi, điểm số) môn CTRR của lớp “K12”, sắp xếp
theo tên, họ học viên.*/
--Cách 1
SELECT KQT.MAHV,  HO, TEN, LANTHI, DIEM
FROM HOCVIEN HV, KETQUATHI KQT
WHERE MAMH = 'CTRR' AND MALOP = 'K12'
AND HV.MAHV = KQT.MAHV
ORDER BY TEN, HO 

--Cách 2
SELECT KQT.MAHV,  HO, TEN, LANTHI, DIEM
FROM HOCVIEN HV INNER JOIN KETQUATHI KQT ON HV.MAHV = KQT.MAHV
WHERE KQT.MAMH = 'CTRR' AND MALOP = 'K12'
ORDER BY TEN, HO ASC

/*Câu 3: In ra danh sách những học viên (mã học viên, họ tên) và những môn học mà học viên đó thi lần thứ
nhất đã đạt.*/
--Cách 1
SELECT HV.MAHV, HO, TEN, MAMH
FROM HOCVIEN HV, KETQUATHI KQT
WHERE LANTHI = 1 AND KQUA = 'Dat'
AND HV.MAHV = KQT.MAHV

--Cách 2
SELECT HV.MAHV, HO, TEN, MAMH
FROM HOCVIEN HV INNER JOIN KETQUATHI KQT ON HV.MAHV = KQT.MAHV
WHERE LANTHI = 1 AND KQUA = 'Dat'

/*Câu 4: In ra danh sách học viên (mã học viên, họ tên) của lớp “K11” thi môn CTRR không đạt (ở lần thi 1).*/
SELECT HV.MAHV, HO, TEN
FROM HOCVIEN HV INNER JOIN KETQUATHI KQT
	ON HV.MAHV = KQT.MAHV
WHERE MAMH = 'CTRR' AND LANTHI = 1
AND MALOP = 'K11' AND KQUA = 'Khong dat'

/*Câu 5: * Danh sách học viên (mã học viên, họ tên) của lớp “K” thi môn CTRR không đạt (ở tất cả các lần
thi).*/
SELECT HV.MAHV, HO, TEN
FROM HOCVIEN HV JOIN KETQUATHI KQT ON HV.MAHV = KQT.MAHV
WHERE  MALOP LIKE 'K%' AND MAMH = 'CTRR'
AND KQUA = 'Khong dat'
EXCEPT
SELECT HV.MAHV, HO, TEN
FROM HOCVIEN HV JOIN KETQUATHI KQT ON HV.MAHV = KQT.MAHV
WHERE  MALOP LIKE 'K%' AND MAMH = 'CTRR'
AND KQUA = 'Dat'

/*Câu 6: Tìm tên những môn học mà giáo viên có tên “Tran Tam Thanh” dạy trong học kỳ 1 năm 2006.*/
SELECT DISTINCT MH.MAMH
FROM (GIAOVIEN GV INNER JOIN GIANGDAY GD ON GV.MAGV = GD.MAGV)
		INNER JOIN MONHOC MH ON MH.MAMH = GD.MAMH
WHERE HOTEN = 'Tran Tam Thanh'
AND HOCKY = 1
AND NAM = 2006

/*Câu 7: Tìm những môn học (mã môn học, tên môn học) mà giáo viên chủ nhiệm lớp “K11” dạy trong học
kỳ 1 năm 2006.*/
--Cách 1:
SELECT MH.MAMH, TENMH
FROM MONHOC MH JOIN GIANGDAY GD ON MH.MAMH = GD.MAMH
WHERE HOCKY = 1
AND NAM = 2006
AND GD.MAGV IN( SELECT MAGVCN
				FROM LOP
				WHERE MALOP = 'K11')

--Cách 2:
SELECT MH.MAMH, TENMH
FROM (MONHOC MH JOIN GIANGDAY GD ON MH.MAMH = GD.MAMH)
		JOIN LOP L ON L.MAGVCN = GD.MAGV
WHERE HOCKY = 1
AND NAM = 2006
AND L.MALOP = 'K11'

/*Câu 8: Tìm họ tên lớp trưởng của các lớp mà giáo viên có tên “Nguyen To Lan” dạy môn “Co So Du Lieu”.*/
SELECT HO, TEN
FROM (((LOP L JOIN HOCVIEN HV ON L.TRGLOP = HV.MAHV)
		 JOIN GIAOVIEN GV ON GV.MAGV = L.MAGVCN)
			 JOIN GIANGDAY GD ON GD.MAGV = GV.MAGV)
				 JOIN MONHOC MH ON MH.MAMH = GD.MAMH
WHERE HOTEN = 'Nguyen To Lan'
AND TENMH = 'Co So Du Lieu'

/*Câu 9: In ra danh sách những môn học (mã môn học, tên môn học) phải học liền trước môn “Co So Du
Lieu”.*/
SELECT DK.MAMH_TRUOC
FROM DIEUKIEN DK JOIN MONHOC MH ON DK.MAMH = MH.MAMH
WHERE TENMH = 'Co So Du Lieu'

/*Câu 10: Môn “Cau Truc Roi Rac” là môn bắt buộc phải học liền trước những môn học (mã môn học, tên
môn học) nào.*/
SELECT DK.MAMH, TENMH
FROM DIEUKIEN DK JOIN MONHOC MH ON DK.MAMH_TRUOC = MH.MAMH
WHERE TENMH = 'Cau Truc Roi Rac'

/*Câu 11: Tìm họ tên giáo viên dạy môn CTRR cho cả hai lớp “K11” và “K12” trong cùng học kỳ 1 năm 2006.*/
--Cách 1 
SELECT DISTINCT HOTEN
FROM GIANGDAY GD JOIN GIAOVIEN GV ON GD.MAGV = GV.MAGV
WHERE MALOP IN ('K11', 'K12')
AND HOCKY = 1 AND NAM = 2006 
AND MAMH = 'CTRR'

--Cách 2
SELECT HOTEN
FROM GIANGDAY GD JOIN GIAOVIEN GV ON GD.MAGV = GV.MAGV
WHERE MALOP = 'K11' AND MAMH = 'CTRR'
AND HOCKY = 1 AND NAM = 2006
INTERSECT
SELECT HOTEN
FROM GIANGDAY GD JOIN GIAOVIEN GV ON GD.MAGV = GV.MAGV
WHERE MALOP = 'K12' AND MAMH = 'CTRR'
AND HOCKY = 1 AND NAM = 2006

/*Câu 12: Tìm những học viên (mã học viên, họ tên) thi không đạt môn CSDL ở lần thi thứ 1 nhưng chưa thi
lại môn này.*/
SELECT HV.MAHV, HO, TEN
FROM HOCVIEN HV JOIN KETQUATHI KQT
	ON HV.MAHV = KQT.MAHV
WHERE KQUA = 'Khong dat'
AND MAMH = 'CSDL'
AND HV.MAHV NOT IN(  SELECT DISTINCT MAHV /*DS SV thi lại*/
					 FROM KETQUATHI
					 WHERE MAMH = 'CSDL' AND LANTHI >=2)

/*Câu 13: Tìm giáo viên (mã giáo viên, họ tên) không được phân công giảng dạy bất kỳ môn học nào.*/
--Cách 1
SELECT MAGV, HOTEN
FROM GIAOVIEN
EXCEPT
SELECT GV.MAGV, HOTEN
FROM GIAOVIEN GV INNER JOIN GIANGDAY GD 
	ON GV.MAGV = GD.MAGV

--Cách 2
SELECT MAGV, HOTEN
FROM GIAOVIEN
WHERE MAGV NOT IN(  SELECT MAGV
					FROM GIANGDAY)

/*Câu 14: Tìm giáo viên (mã giáo viên, họ tên) không được phân công giảng dạy bất kỳ môn học nào thuộc
khoa giáo viên đó phụ trách.*/
SELECT MAGV, HOTEN
FROM GIAOVIEN
WHERE MAGV NOT IN(	SELECT DISTINCT GD.MAGV
					FROM (GIANGDAY GD INNER JOIN MONHOC MH ON GD.MAMH = MH.MAMH)
								INNER JOIN GIAOVIEN GV ON GV.MAGV = GD.MAGV
					WHERE MH.MAKHOA = GV.MAKHOA)

/*Câu 15: Tìm họ tên các học viên thuộc lớp “K11” thi một môn bất kỳ quá 3 lần vẫn “Khong dat” hoặc thi lần
thứ 2 môn CTRR được 5 điểm.*/
SELECT HO, TEN
FROM HOCVIEN HV JOIN KETQUATHI KQT ON HV.MAHV = KQT.MAHV
WHERE MALOP = 'K11'
AND ((LANTHI = 3 AND KQUA = 'Khong dat')
OR (LANTHI = 2 AND KQUA = 'Dat'))

/*Câu 16: Tìm họ tên giáo viên dạy môn CTRR cho ít nhất hai lớp trong cùng một học kỳ của một năm học.*/
SELECT HOTEN
FROM GIAOVIEN GV JOIN GIANGDAY GD ON GV.MAGV = GD.MAGV
WHERE MAMH = 'CTRR'
GROUP BY NAM, HOCKY, HOTEN
HAVING COUNT(*) >= 2

/*Câu 17: Danh sách học viên và điểm thi môn CSDL (chỉ lấy điểm của lần thi sau cùng).*/ --Kiểm tra lại
SELECT HV.MAHV, HO, TEN, DIEM
FROM KETQUATHI KQT JOIN HOCVIEN HV ON HV.MAHV = KQT.MAHV
WHERE MAMH = 'CSDL'
AND LANTHI >= ALL(	SELECT LANTHI
					FROM KETQUATHI KQT2
					WHERE KQT2.MAHV = KQT.MAHV)

/*Câu 18: Danh sách học viên và điểm thi môn “Co So Du Lieu” (chỉ lấy điểm cao nhất của các lần thi).*/ --Kiểm tra lại
SELECT HV.MAHV, HO, TEN, DIEM
FROM (KETQUATHI KQT JOIN HOCVIEN HV ON HV.MAHV = KQT.MAHV)
		JOIN MONHOC MH ON MH.MAMH = KQT.MAMH
WHERE TENMH = 'Co So Du Lieu'
AND DIEM >= ALL(	SELECT DIEM
					FROM KETQUATHI KQT2
					WHERE KQT2.MAHV = KQT.MAHV)
					
/*Câu 19: Khoa nào (mã khoa, tên khoa) được thành lập sớm nhất.*/
SELECT TOP 1 WITH TIES MAKHOA, TENKHOA
FROM KHOA
ORDER BY NGTLAP ASC

/*Câu 20: Có bao nhiêu giáo viên có học hàm là “GS” hoặc “PGS”.*/
SELECT HOCHAM, COUNT(MAGV) SoGV
FROM GIAOVIEN
WHERE HOCHAM = 'GS' OR HOCHAM = 'PGS'
GROUP BY HOCHAM

/*Câu 21: Thống kê có bao nhiêu giáo viên có học vị là “CN”, “KS”, “Ths”, “TS”, “PTS” trong mỗi khoa.*/
SELECT MAKHOA, COUNT(MAGV) SoGV
FROM GIAOVIEN
GROUP BY MAKHOA

/*Câu 22: Mỗi môn học thống kê số lượng học viên theo kết quả (đạt và không đạt).*/
SELECT MAMH, KQUA, COUNT(MAHV) SOHV
FROM KETQUATHI
GROUP BY MAMH, KQUA

/*Câu 23: Tìm giáo viên (mã giáo viên, họ tên) là giáo viên chủ nhiệm của một lớp, đồng thời dạy cho lớp đó ít
nhất một môn học.*/
--Check data đúng, chưa check code
SELECT GV.MAGV, HOTEN, GD.MALOP, COUNT(MAMH) SOMH
FROM (LOP L JOIN GIANGDAY GD ON L.MALOP = GD.MALOP)
		JOIN GIAOVIEN GV ON L.MAGVCN = GV.MAGV
WHERE GV.MAGV = GD.MAGV
GROUP BY GV.MAGV, HOTEN, GD.MALOP
HAVING COUNT(MAMH) >= 1

/*Câu 24: Tìm họ tên lớp trưởng của lớp có sỉ số cao nhất.*/
--Cách 1
SELECT TOP 1 WITH TIES HO, TEN, SISO
FROM LOP L JOIN HOCVIEN HV ON L.TRGLOP = HV.MAHV
ORDER BY SISO DESC

--Cách 2
SELECT HO, TEN, SISO
FROM LOP L JOIN HOCVIEN HV ON L.TRGLOP = HV.MAHV
WHERE SISO >= ALL( SELECT SISO FROM LOP)

/*Câu 25: * Tìm họ tên những LOPTRG thi không đạt quá 3 môn (mỗi môn đều thi không đạt ở tất cả các lần thi).*/ --Chưa được kiểm tra
SELECT HO, TEN, COUNT(MAMH) SOMONKHONGDAT
FROM HOCVIEN HV JOIN KETQUATHI KQT ON HV.MAHV = KQT.MAHV
WHERE HV.MAHV IN (SELECT TRGLOP FROM LOP)
AND KQUA = 'Khong dat' AND LANTHI = 3
GROUP BY HO, TEN
HAVING COUNT(MAMH) >= 3

/*Câu 26: Tìm học viên (mã học viên, họ tên) có số môn đạt điểm 9,10 nhiều nhất.*/
--Cách 1
SELECT TOP 1 WITH TIES HV.MAHV, HO, TEN, COUNT(MAMH) SOMH
FROM HOCVIEN HV JOIN KETQUATHI KQT ON HV.MAHV = KQT.MAHV
WHERE DIEM = 9 OR DIEM = 10
GROUP BY HV.MAHV, HO, TEN
ORDER BY SOMH DESC

--Cách 2
SELECT HV.MAHV, HO, TEN, COUNT(MAMH) SOMH
FROM HOCVIEN HV JOIN KETQUATHI KQT ON HV.MAHV = KQT.MAHV
WHERE DIEM = 9 OR DIEM = 10
GROUP BY HV.MAHV, HO, TEN
HAVING COUNT(MAMH) >= ALL (	SELECT COUNT(MAMH)
							FROM KETQUATHI
							WHERE DIEM = 9 OR DIEM = 10
							GROUP BY MAHV)

/*Câu 27: Trong từng lớp, tìm học viên (mã học viên, họ tên) có số môn đạt điểm 9,10 nhiều nhất.*/
--Chưa hiểu, cần làm lại
SELECT HV1.MAHV, HO, TEN, MALOP, COUNT(MAMH) SOMH
FROM HOCVIEN HV1 JOIN KETQUATHI KQT1 ON HV1.MAHV = KQT1.MAHV
WHERE DIEM = 9 OR DIEM = 10
GROUP BY MALOP, HV1.MAHV, HO, TEN
HAVING COUNT(MAMH) >= ALL(	SELECT COUNT(MAMH)
							FROM HOCVIEN HV2 JOIN KETQUATHI KQT2 ON HV2.MAHV = KQT2.MAHV
							WHERE (DIEM = 9 OR DIEM = 10)
							AND HV1.MALOP = HV2.MALOP
							GROUP BY HV2.MAHV, MALOP)

/*Câu 28: Trong từng học kỳ của từng năm, mỗi giáo viên phân công dạy bao nhiêu môn học, bao nhiêu lớp.*/
SELECT MAGV, HOCKY, NAM, COUNT(DISTINCT MAMH) SOMONHOC, COUNT(DISTINCT MALOP) SOLOP
FROM GIANGDAY 
GROUP BY MAGV, HOCKY, NAM

/*Câu 29: Trong từng học kỳ của từng năm, tìm giáo viên (mã giáo viên, họ tên) giảng dạy nhiều nhất.*/
SELECT GV1.MAGV, HOTEN, HOCKY, NAM, COUNT(*) SOLANGIANGDAY
FROM GIANGDAY GD1 JOIN GIAOVIEN GV1 ON GD1.MAGV = GV1.MAGV
GROUP BY GV1.MAGV, HOTEN, HOCKY, NAM
HAVING COUNT(*) >= ALL (	SELECT COUNT(*)
							FROM GIANGDAY GD2 JOIN GIAOVIEN GV2 ON GD2.MAGV = GV2.MAGV
							WHERE GD1.HOCKY = GD2.HOCKY AND GD1.NAM= GD2.NAM
							GROUP BY GV2.MAGV, HOTEN, HOCKY, NAM)

/*Câu 30: Tìm môn học (mã môn học, tên môn học) có nhiều học viên thi không đạt (ở lần thi thứ 1) nhất.*/
--Cách 1
SELECT TOP 1 WITH TIES MH.MAMH, TENMH, COUNT(MAHV) SOHVKHONGDAT
FROM MONHOC MH JOIN KETQUATHI KQT ON MH.MAMH = KQT.MAMH
WHERE LANTHI = 1 AND KQUA = 'Khong dat'
GROUP BY MH.MAMH, TENMH
ORDER BY SOHVKHONGDAT DESC

--Cách 2
SELECT  MH.MAMH, TENMH, COUNT(MAHV) SOHVKHONGDAT
FROM MONHOC MH JOIN KETQUATHI KQT ON MH.MAMH = KQT.MAMH
WHERE LANTHI = 1 AND KQUA = 'Khong dat'
GROUP BY MH.MAMH, TENMH
HAVING COUNT(MAHV) >= ALL (	SELECT COUNT(MAHV) 
							FROM KETQUATHI
							WHERE LANTHI = 1 AND KQUA = 'Khong dat'
							GROUP BY MAMH)

/*Câu 31: Tìm học viên (mã học viên, họ tên) thi môn nào cũng đạt (chỉ xét lần thi thứ 1).*/
SELECT DISTINCT HV.MAHV, HO, TEN
FROM HOCVIEN HV JOIN KETQUATHI KQT ON HV.MAHV = KQT.MAHV
WHERE HV.MAHV NOT IN(	SELECT DISTINCT MAHV
						FROM KETQUATHI
						WHERE LANTHI = 1 AND KQUA = 'Khong dat')

/*Câu 32: * Tìm học viên (mã học viên, họ tên) thi môn nào cũng đạt (chỉ xét lần thi sau cùng).*/
SELECT DISTINCT HV.MAHV, HO, TEN
FROM HOCVIEN HV JOIN KETQUATHI KQT ON HV.MAHV = KQT.MAHV
WHERE KQUA = 'Dat'
GROUP BY HV.MAHV, HO, TEN
HAVING COUNT(MAMH) = (	SELECT COUNT(DISTINCT MAMH)
						FROM KETQUATHI)

SELECT DISTINCT HV.MAHV,HO,TEN,COUNT(MAMH) AS SOMONDAT
FROM (SELECT MAHV,MAMH,KQUA,MAX(LANTHI) AS MAXLANTHI
	FROM KETQUATHI
	GROUP BY MAHV,MAMH,KQUA) AS KQM JOIN HOCVIEN HV ON KQM.MAHV = HV.MAHV
WHERE KQUA = 'Dat'
GROUP BY HV.MAHV,HO,TEN
HAVING COUNT(MAMH) IN (SELECT COUNT(DISTINCT (MAMH)) AS SOMONDAT
					FROM KETQUATHI KQ2
					WHERE HV.MAHV = KQ2.MAHV
					GROUP BY MAHV)